apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/elasticsearch/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-config-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/elasticsearch/config
