apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: elasticsearch-data-pv
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-config-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: elasticsearch-config-pv
  resources:
    requests:
      storage: 128Mi
