apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: ELASTICSEARCH
  type: NodePort
  ports:
    - name: elasticsearch-http-port
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30200
    - name: elasticsearch-binary-port
      protocol: TCP
      port: 9300
      targetPort: 9300
      nodePort: 30300
