apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-config-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: kibana-config-pv
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: kibana-data-pv
  resources:
    requests:
      storage: 16Gi
