apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-config-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/kibana/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-data-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/kibana/data
