apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KIBANA
  template:
    metadata:
      name: kibana-lab
      labels:
        app: KIBANA
    spec:
      hostname: kibana
      containers:
        - name: kibana
          image: kibana:8.5.2
          ports:
            - containerPort: 5601
          volumeMounts:
            - mountPath: /usr/share/kibana/config
              name: kibana-config-vol
            - mountPath: /usr/share/kibana/data
              name: kibana-data-vol
      volumes:
        - name: kibana-config-vol
          persistentVolumeClaim:
            claimName: kibana-config-pvc
        - name: kibana-data-vol
          persistentVolumeClaim:
            claimName: kibana-data-pvc
      restartPolicy: Always
