apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    app: KIBANA
  type: NodePort
  ports:
    - name: kibana-port
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30601
